name: Test

on:
  push:
    branches: "**"
    pull_request:

jobs:
  test-linux:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.7"
    - run: swift --version
    - uses: actions/checkout@v2
    - run: swift test
